name: tfsec scan

on:
  push:
    branches: ["dev", "staging", "prod"]
  pull_request:
    branches: ["prod"]

jobs:
  tfsec:
    name: Run tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          args: --format sarif
